### ISSUE TITLE
Deploy to netlify

### ISSUE THREAD

**Issue by YerkoPalma** [YerkoPalma/choo-phaser#6]
### TODO

- [x] Add build packages and scripts
- [x] Run `netlify init`
- [x] Fix paths for production
- [ ] ~~Fix missing fonts~~ Find some good fallbacks
- [ ] Make responsive 
- [x] Add enviroment variables
